Fix publish test report failed

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -61,19 +61,11 @@ jobs:
         with:
           arguments: clean build test --info  # Running all necessary gradle commands in one step
 
-      - name: Gradle Clean
-        run: ./gradlew clean
-
-      - name: Gradle Build & Test
-        run: ./gradlew build --info
-
-      - name: Run Tests and Generate Report
-        run: ./gradlew test --info
-
       - name: Publish Test Report
-        uses: dorny/test-reporter@v1  # Action to display test results
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
         with:
           name: Gradle Tests
-          path: build/test-results/test/*.xml  # Path to your test result XML files
-          reporter: junit  # Specify JUnit as the report format
-          fail-on-error: false  # Continue the workflow even if there are test failures
+          path: build/test-results/test/*.xml
+          reporter: java-junit
+          fail-on-error: false
